#%RAML 1.0 DataType
properties:
  id:
    required: true
    type: number
  owner_id:
    required: true
    type: number
  parent_folder_id: number
  name:
    required: true
    type: string
  path: string
  created_at: datetime
  modified_at: datetime
