#!/bin/bash

source ./app_config

if [[ "$?" == "1" ]]; then  # app_config needs to be set up
  exit 1
fi

read -p "username or user ID: " user_identifier

response=$(curl -k \
  -H "Content-Type: application/json" \
  -X GET \
  -b $INFO3103_COOKIE \
  --silent \
  $INFO3103_URL/users/$user_identifier)

echo ""

if [[ $response == *'{"id":'*'"username":'*'"name":'*'"email":'* ]]; then
  echo "✓ Successfully retrieved user details!"
elif  [[ $response == *'Resource not found'* ]]; then
  echo "✘ Failed to retrieve user details - requested user does not exist."
elif  [[ $response == *'Authentication Required'* ]]; then
  echo "✘ Failed to retrieve user details. Have you logged in yet?"
fi

echo "=>  $response"
