#!/bin/bash

source ./app_config

if [[ "$?" == "1" ]]; then  # app_config needs to be set up
  exit 1
fi

read -p "username: " username
read -s -p "password: " password

echo ""

response=$(curl -k \
  -H "Content-Type: application/json" \
  -d '{"username": "'$username'", "password": "'$password'"}' \
  -c $INFO3103_COOKIE \
  --silent \
  $INFO3103_URL/login)

echo ""

if [[ $response == '{"message": "successfully authenticated user"}' ]]; then
  echo "✓ Successfully authenticated!"
else
  echo "✘ Authentication failed."
fi

echo "=>  $response"
