#!/bin/bash

source ./app_config

if [[ "$?" == "1" ]]; then  # app_config needs to be set up
  exit 1
fi

response=$(curl -k \
  -H "Content-Type: application/json" \
  -X DELETE \
  -b $INFO3103_COOKIE \
  --silent \
  $INFO3103_URL/login)

echo ""

if [[ $response == '' ]]; then
  echo "✓ Successfully logged out!"
else
  echo "✘ Logout failed, somehow."
fi

echo "=>  $response"
