#!/bin/bash

source ./app_config

if [[ "$?" == "1" ]]; then  # app_config needs to be set up
  exit 1
fi

read -p "username or user ID: " user_identifier
read -p "enter a file id to rename: " file_id
read -p "enter a new filename for the file: " new_filename

response=$(curl -k \
  -H "Content-Type: application/json" \
  -X PUT \
  -d '{"name": "'$new_filename'"}' \
  -b $INFO3103_COOKIE \
  --silent \
  $INFO3103_URL/users/$user_identifier/files/$file_id)

echo ""

if [[ $response == *'"name": "$new_filename"'* ]]; then
  echo "✓ Successfully renamed file!"
elif  [[ $response == *'Authentication Required'* ]]; then
  echo "✘ Failed to rename file. Have you logged in yet?"
elif  [[ $response == *'Permission Denied'* ]]; then
  echo "✘ Failed to rename file. Are you trying to rename someone else's file?"
elif  [[ $response == *'Resource not found'* ]]; then
  echo "✘ Failed to rename file. You requested a file that does not exist."
else
  echo "✘ File upload failed."
fi

echo "=>  $response"
