#!/bin/bash

source ./app_config

if [[ "$?" == "1" ]]; then  # app_config needs to be set up
  exit 1
fi

read -p "username or user ID: " user_identifier
read -p "enter a file path to upload: " file_path

response=$(curl -k \
  -H "Content-Type: multipart/form-data" \
  -X POST \
  -F "file=@$file_path" \
  -b $INFO3103_COOKIE \
  --silent \
  $INFO3103_URL/users/$user_identifier/files)

echo ""

if [[ $response == '{"resourceId":'* ]]; then
  echo "✓ Successfully uploaded file!"
else
  echo "✘ File upload failed."
fi

echo "=>  $response"
