DROP TABLE IF EXISTS files;

CREATE TABLE files (
    uuid VARCHAR(36) NOT NULL PRIMARY KEY,
    folder_id VARCHAR(36) DEFAULT NULL,
    owner_id VARCHAR(36) NOT NULL,
    name VARCHAR(255) NOT NULL,
    path VARCHAR(4096) NOT NULL,
    extension VARCHAR(12) DEFAULT NULL,
    hash VARCHAR(255) DEFAULT NULL, /* File integrity */
    size INT UNSIGNED DEFAULT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
