#!/bin/bash

source ../app_config

if [[ "$?" == "1" ]]; then  # app_config needs to be set up
  exit 1
fi

source ../lib

read -p "username or user ID: " user_identifier
read -p "enter a file id to delete: " file_id

delete_file
list_user_files

if [[ $response == *'id\": '$file_id','* ]]; then
  echo "✘ Failed to delete file."
elif  [[ $response == *'Authentication Required'* ]]; then
  echo "✘ Failed to delete file. Have you logged in yet?"
elif  [[ $response == *'Permission Denied'* ]]; then
  echo "✘ Failed to delete file. Are you trying to delete someone else's file?"
elif  [[ $response == *'Resource not found'* ]]; then
  echo "✘ Failed to delete file. You requested a file that does not exist."
else
  echo "✓ Successfully deleted file!"
fi

echo "=>  $response"
