#!/bin/bash

source ../app_config

if [[ "$?" == "1" ]]; then  # app_config needs to be set up
  exit 1
fi

source ../lib

read -p "username or user ID: " user_identifier

get_user_details

echo ""

if [[ $response == *'{"id":'*'"username":'*'"name":'*'"email":'* ]]; then
  echo "✓ Successfully retrieved user details!"
elif  [[ $response == *'Resource not found'* ]]; then
  echo "✘ Failed to retrieve user details - requested user does not exist."
elif  [[ $response == *'Authentication Required'* ]]; then
  echo "✘ Failed to retrieve user details. Have you logged in yet?"
fi

echo "=>  $response"
