#!/bin/bash

source ../app_config

if [[ "$?" == "1" ]]; then  # app_config needs to be set up
  exit 1
fi

source ../lib

read -p "username or user ID: " user_identifier

list_user_files

echo ""

if [[ $response == '{"items":'* ]]; then
  echo "✓ Successfully retrieved your file list!"
elif  [[ $response == *'Authentication Required'* ]]; then
  echo "✘ Failed to retrieve file list. Have you logged in yet?"
elif  [[ $response == *'Resource not found'* ]]; then
  echo "✘ Failed to retrieve file list. You requested a user that does not exist."
else
  echo "✘ Failed to retrieve file list for an unknown reason."
fi

echo "=>  $response"
