#!/bin/bash

source ../app_config

if [[ "$?" == "1" ]]; then  # app_config needs to be set up
  exit 1
fi

source ../lib

read -p "username: " username
read -s -p "password: " password

echo ""

log_user_in

echo ""

if [[ $response == '{"message": "successfully authenticated user"}' ]]; then
  echo "✓ Successfully authenticated!"
else
  echo "✘ Authentication failed."
fi

echo "=>  $response"
