#!/bin/bash

source ../app_config

if [[ "$?" == "1" ]]; then  # app_config needs to be set up
  exit 1
fi

source ../lib

log_user_out

echo ""

if [[ $response == '' ]]; then
  echo "✓ Successfully logged out!"
else
  echo "✘ Logout failed, somehow."
fi

echo "=>  $response"
