#!/bin/bash

source ../app_config

if [[ "$?" == "1" ]]; then  # app_config needs to be set up
  exit 1
fi

source ../lib

read -p "username or user ID: " user_identifier
read -p "enter a file id to rename: " file_id
read -p "enter a new filename for the file: " new_filename

rename_file

echo ""

if [[ $response == *'"name": "$new_filename"'* ]]; then
  echo "✓ Successfully renamed file!"
elif  [[ $response == *'Authentication Required'* ]]; then
  echo "✘ Failed to rename file. Have you logged in yet?"
elif  [[ $response == *'Permission Denied'* ]]; then
  echo "✘ Failed to rename file. Are you trying to rename someone else's file?"
elif  [[ $response == *'Resource not found'* ]]; then
  echo "✘ Failed to rename file. You requested a file that does not exist."
else
  echo "✘ File renaming failed."
fi

echo "=>  $response"
