#!/bin/bash

source ../app_config

if [[ "$?" == "1" ]]; then  # app_config needs to be set up
  exit 1
fi

source ../lib

read -p "username or user ID: " user_identifier
read -p "enter a file path to upload: " file_path

upload_file

echo ""

if [[ $response == '{"resourceId":'* ]]; then
  echo "✓ Successfully uploaded file!"
else
  echo "✘ File upload failed."
fi

echo "=>  $response"
